### ISSUE TITLE
Error on soft reboot

### ISSUE THREAD

**Issue by EagleOwl3** [dr-mod/pico-solar-system#11]
Hello,

I do have a DS3231 module, but get this output:

aceback (most recent call last):
  File "main.py", line 175, in <module>
  File "main.py", line 77, in main
  File "ds3231.py", line 19, in __init__
OSError: [Errno 5] EIO

>>> rtc=ds3231.ds3231()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ds3231.py", line 19, in __init__
OSError: [Errno 5] EIO

Micropython 1.18.1

Just to add, the RTC module is the 'Precision RTC Module for Raspberry Pi Pico (DS3231). https://thepihut.com/products/precision-rtc-module-for-raspberry-pi-pico-ds3231

Many thanks.

**Comment by EagleOwl3** [comment]
Apologies - faulty RTC. Should of got the multimeter out sooner!
